title: New Title
author: GitHub training user
email: test-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Not even sure what to type here, but it's training.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
